### ISSUE TITLE
Navbar plugin does not work on dynamically inserted content 

### ISSUE THREAD

**Issue by gieglas** [VizuaaLOG/BulmaJS#133]
Versions
BulmaJS: 0.12.0
Browser: Chrome latest
Operating system: Windows 10

Describe the bug
When dynamically inserting a navbar, on mobile view when clicking the hamburger button, the dropdown with the menu items do not appear? Specifically if the following part of the code is not included when the page loads, but is rendered dynamically, the hamburger button does not work: 

```html
<button role="button" class="navbar-burger button is-white" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
                <span aria-hidden="true"></span>
                <span aria-hidden="true"></span>
                <span aria-hidden="true"></span>
            </button>
```

Expected behavior
Dynamically inserted navbar, behave as expected.

Thank you kindly.

**Comment by VizuaaLOG** [comment]
Hey @gieglas 👋,

While this isn't documented very well. The navbar can be instantiated manually for this use case.

When inserting the navbar dynamically you should be able to call something like below, once it's been inserted into the document.

```javascript
Bulma(element).navbar({
    sticky: element.hasAttribute('data-sticky') ? true : false,
    stickyOffset: element.hasAttribute('data-sticky-offset') ? element.getAttribute('data-sticky-offset') : 0,
    hideOnScroll: element.hasAttribute('data-hide-on-scroll') ? true : false,
    tolerance: element.hasAttribute('data-tolerance') ? element.getAttribute('data-tolerance') : 0,
    hideOffset: element.hasAttribute('data-hide-offset') ? element.getAttribute('data-hide-offset') : null,
    shadow: element.hasAttribute('data-sticky-shadow') ? true : false
});
```

I've taken the exact code the Navbar uses internally to demonstrate. However you can tweak however you like, in this instance using data attributes is also optional since you're only having to cater for you use case. 

Let me know how you get on 😁

**Comment by gieglas** [comment]
Hi, 

Thank you for your quick response. Yes it worked perfectly, I thought there was a way to instantiate the navbar but wasn't really sure :-).

Again thank you for your help.

**Comment by VizuaaLOG** [comment]
No worries, glad it worked for you 😊
