### ISSUE TITLE
[Chore] Release problems

### ISSUE THREAD

**Issue by noraj** [VizuaaLOG/BulmaJS#97]
## Issue n°1

Minor releases lack changelogs.

![image](https://user-images.githubusercontent.com/16578570/72755070-e3879400-3bc9-11ea-9d11-1f054bb44bf6.png)

## Issue n°2

v0.10.2 was release on npm but there is not git tag on the source repo

![image](https://user-images.githubusercontent.com/16578570/72755095-f4d0a080-3bc9-11ea-91e6-52c625126d16.png)

**Comment by noraj** [comment]
Related issue https://gitlab.com/noraj/hacker-profile/merge_requests/12

**Comment by VizuaaLOG** [comment]
Hey @noraj, thank you for flagging this. I'll ensure everything is kept consistent with future releases as I've clearly missed some steps with this :pensive:

There is a changelog.md file in every release that should contain what has changed etc. I'll get the 0.10.3 tag docs updated later today to reflect this.

0.10.3 was a minor default value change for the hideOffset it should have been null instead of 0.

Hope this helps :blush:
